require 'rawr'
Dir.glob("tasks/**/*.rake").each do |rake_file|
  load File.expand_path(File.dirname(__FILE__) + "/" + rake_file)
end



desc "Clean and jar then execute."
task :clean_jar_run  => ['rawr:clean', 'rawr:jar'] do
puts "We are using #{Config::CONFIG["target_os"]  }"
  case Config::CONFIG["target_os"]  
    when /linux/i
      puts "Seems we are on linux: #{Config::CONFIG["target_os"]}"
    Dir.chdir "package/jar" do
      sh "LD_LIBRARY_PATH=lib/java/; java  -Djava.library.path=lib/java/   -Dbluecove.jsr82.psm_minimum_off=true  -jar BareWiiRemoteJ.jar "
    end
    when /darwin/i
      # puts "Not ready for OSX"
    Dir.chdir "package/jar" do
      sh "LD_LIBRARY_PATH=lib/java/; java  -Djava.library.path=lib/java/   -Dbluecove.jsr82.psm_minimum_off=true  -jar BareWiiRemoteJ.jar "
    end
    else
    puts "Currently only defined for linux"
  end
end
